### ISSUE TITLE
ID's/ Classes

### ISSUE THREAD

**Issue by ghost** [X-Track/dev#4]
Ik geloof dat we helemaal geen ID's mochten gebruiken en het liefst zo min mogelijk classes. Maar dit weet ik niet 100% zeker!

https://github.com/X-Track/dev/blob/af229984e8ec849680bb2fc3cdbe4ad999ddae13/index.html#L99

**Comment by X-Track** [comment]
dit mag wel maar ik heb deze web gehaald want heb hem niet gebruikt
